### ISSUE TITLE
Presets!

### ISSUE THREAD

**Issue by jatinchowdhury18** [jatinchowdhury18/AnalogTapeModel#30]
For the next release, I'd like to include some presets. If you'd like to contribute your own preset, please copy the template below, and fill in your own parameter values:

```
Input Gain [dB]: 0.0
Output Gain [dB]: 0.0
Dry/Wet: 100.0
Hysteresis:
  Oversampling: 2x
  Bias: 0.5
  Saturation: 0.5
  Drive: 0.5
  Mode: RK2
Tone:
  Bass: 0.0
  Treble: 0.0
Loss:
  Speed [ips]: 15.0
  Spacing [cm]: 0.00001
  Thickness [cm]: 0.00001
  Gap [cm]: 0.00001
Degrade:
  Depth: 0.0
  Amount: 0.0
  Variance: 0.0
Chew:
  Depth: 0.0
  Freq: 0.0
  Variance: 0.0
Flutter:
  Rate: 0.3
  Depth: 0.0
Wow:
  Rate: 0.2
  Depth: 0.0
```
